name: CI/CD
on:
  push:
    paths:
      - src/**
      - features/**
      - stories/**
      - package.json
      - package-lock.json
      - .github/workflows/CICD.yml

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Retrieve dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: js-${{ hashFiles('package-lock.json') }}
          restore-keys: js-
      - name: Install missing dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run tests
        run: npm test

  storybook:
    name: Publish Storybook to Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Retrieve dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: js-${{ hashFiles('package-lock.json') }}
          restore-keys: js-
      - name: Install missing dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Publish
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          exitOnceUploaded: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ tests, storybook ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy via SSH
        run: |
          eval `ssh-agent`
          ssh-add - <<< "${{ secrets.CICDSSH }}"
          mkdir ~/.ssh
          ssh-keyscan speely.net >> ~/.ssh/known_hosts
          scp -r ./src/* github@speely.net:~/components/$([[ $GITHUB_REF == refs/tags/* ]] && echo "stable" || echo "latest")

